version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    # - method: pip
    #   path: git+https://github.com/comfort-mode-toolkit/cm-colors.git

sphinx:
  configuration: conf.py
